# Generated by Django 4.2.9 on 2024-06-01 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="precio_total",
        ),
        migrations.AddField(
            model_name="producto",
            name="existencia",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="compra",
            name="cantidad",
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name="compra",
            name="fecha_compra",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_caducidad",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
